version: '3.3'

services:
  web:
    image: django_prueba_2
    container_name: django_prueba_container
    restart: always
    network_mode: "host"
    command: >
      bash -c "python manage.py migrate --noinput
      && python manage.py runserver 0.0.0.0:8000"
      